### ISSUE TITLE
Compile error "invalid use of incomplete class QUrl" building TL866_Updater

### ISSUE THREAD

**Issue by phenn** [radiomanV/TL866#15]
Hi,
obviously the _mainwindow.cpp_ got to many cleanups. I could not compile the TL866_Updater. Looks like an include of <QUrl> was gone away. 

This [qurl-missing-fix-patch.txt](https://github.com/radiomanV/TL866/files/1956841/qurl-missing-fix-patch.txt) :

```
--- a/TL866_Updater/QT/mainwindow.cpp
+++ b/TL866_Updater/QT/mainwindow.cpp
@@ -20,6 +20,7 @@
 * USA.
 */
 
+#include <QUrl>
 #include <QWidget>
 #include <QFileDialog>
 #include <QMessageBox>
``` 
fix that problem for me.

Kind Regads,
Peter

**Comment by radiomanV** [comment]
Hi Peter,
Indeed too many cleanups but the QUrl was never included at all and never encountered that error so far. Please tell me where at which line in mainwindow.cpp is that ""invalid use of incomplete class QUrl"" error?

**Comment by phenn** [comment]
Hi radioman,

oh, that was not even one error. When I stash the fix, you can take a look at the 
[build.log](https://github.com/radiomanV/TL866/files/1956961/build.log).
So I guess the missing include was formerly already in one of the removed includes.

Regards,
Peter

**Comment by radiomanV** [comment]
Hi again,
I checked in my two development machines (Linux and windows) and compile is ok without that QUrl include.
Normally you're right, it should be included because of isLocalFile and toLocalFile from the drag and drop events which i have implemented in my last commit (cleanup :)). I don't know why in my setup i don't have these errors that you have (maybe different qt versions). So here is, commited this fix
Thank you.
