### ISSUE TITLE
Programming with a PicKit.

### ISSUE THREAD

**Issue by firew4lker** [radiomanV/TL866#16]
Latest version of software 6.80, bricked the TL866 programmers. Mine is an original one.

Is it possible to use you binary files to program the bootloader and the firmware the tl866 using a pickit?

**Comment by radiomanV** [comment]
Yes you can. Generate a new serial in the firmware section of my updater utility and hit the save button. Now you have the .hex file ready to be programmed by pickit.
Please describe how this brick did happen? 
Maybe next week i will investigate this new 6.80 software(i'm in holyday now) but i tell you, this minipro developer is an idiot because he deliberately brick people devices! I have already saw the brick routine in the minipro software begining with the 6.50 version i think.

**Comment by okurka** [comment]
The brick happened because of the bricking routine that was activated in v6.80. It bricks fake TL866, but also genuine ones that were converted from CS to A and/or have the wrong serial number.
I contacted the developer via email and he released MiniPro v6.81 that has the bricking routine disabled. It still shows that you have a converted device or a 'clone' device if you have the wrong serial number.

I have a backup of the v6.80 software if needed.

**Comment by firew4lker** [comment]
OK. I saw your posts to eevblog and reverted to 6.71 by forcing bootmode. 

They released a new version 6.81 that doesn't brick the device. 

Version 6.81 works (for me) with a startup message that says my unit is a converted one. So, someone bought genuine TL866CS units and converted then to TL866A and sold them.

Is there a serial number that is valid for A variants?

**Comment by firew4lker** [comment]
Version's 6.81 firmware might work but prevents the open source version for GNU/Linux.

**Comment by radiomanV** [comment]
The firmware updater was updated to generate compliant serial codes. It was another crc hidden in the serial.
