### ISSUE TITLE
4116/4164 RAM test support 

### ISSUE THREAD

**Issue by andreacampanella** [radiomanV/TL866#24]
This is sadly a functionality that's not present even in the official software, would be possible to implement it?

**Comment by radiomanV** [comment]
Despite that the TL866 only support static ram for testing, to test those DRAMs an test algorithm should be implemented in firmware. I don't know if such  algorithm can be implemented as bit banging on the client side (as for logic chips for example) because of the dynamic nature of these memories and if you don't refresh the data very quick (2 or 4 ms if i remember correctly) you lose the data.   
This repo is only for my firmware updater and linux wine support. Maybe here in this repo: https://gitlab.com/DavidGriffith/minipro/ 
you can try to open an issue. Who knows. I also contribute to that repo regularly.

**Comment by andreacampanella** [comment]
You are very right, without a firmware implementantion it wouldn't be possible to generate a 4ms ping to refresh the ram. 

I will post it on David Griffith's repo. 

Thank you.

**Comment by andreacampanella** [comment]
Closing this because it's not related to this project.
