### ISSUE TITLE
MiniPro 6.60 request to reflash fireware ... ops ... firmware

### ISSUE THREAD

**Issue by indyucoder** [radiomanV/TL866#6]
Hi, just installed MiniPro 6.60 in wine under lubuntu (16.10)

It request to reflash firmware... maybe hidden check for CS vs A version?
Confirmed ... on an upgarded TL866A V3.xx.x
Reflashing first time report 'read error' and flashes TL866CS V00.0.00
Reflashing again report 'read error' and flashes TL866CS V03.2.80

**Comment by radiomanV** [comment]
This is no hidden check, every new version of the minipro comes with a new firmware, so you must reflash this new firmware to work with this new version.

**Comment by indyucoder** [comment]
Ok, I've run self test and tested some 74LSxxx, a PIC and an AVR and my TL866 works good except that it's back to CS version.

**Comment by radiomanV** [comment]
Hi, this is because you used the 'simple method' to upgrade from CS to A; no problem, use my firmware updater to upgrade to A again and use (if you want) the 'complicated method' to have permanent A upgrade (this will include reflashing the bootloader).
see here: https://www.eevblog.com/forum/blog/eevblog-411-minipro-tl866-universal-programmer-review/msg383943/#msg383943

**Comment by indyucoder** [comment]
Got it.
Thanks a lot.
